import React, { createContext, useContext, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Globe } from 'lucide-react';

interface LanguageContextType {
  language: 'es' | 'en';
  setLanguage: (lang: 'es' | 'en') => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    nav_inicio: "Inicio",
    nav_nosotros: "Nosotros", 
    nav_servicios: "Servicios",
    nav_galeria: "Galería",
    nav_contacto: "Contacto",
    hero_title: "Casa Lago Guijo de Coria",
    hero_subtitle: "Apartamentos rurales en Guijo de Coria, un refugio de paz rodeado de la dehesa extremeña",
    hero_cta: "Reservar Ahora",
    hero_info: "Más información",
    about_title: "Respira. Desconecta. Vuelve a empezar.",
    about_text: "Somos una pareja que decidió transformar este rincón privilegiado de la dehesa extremeña en un refugio para quienes necesitan parar, respirar y reconectar. En Casa Lago Guijo de Coria hemos creado unos apartamentos rurales acogedores y cuidados al detalle, impulsando un modelo de turismo rural responsable y comprometido con la sostenibilidad.",
    about_desire: "Nuestro deseo es que disfrutes de la tranquilidad del campo, el canto de los pájaros y la calma que solo la naturaleza puede ofrecer, poniendo en valor el entorno, sus tradiciones y sus recursos, ya sea en pareja, en familia o con amigos.",
    about_mission_title: "Nuestra Misión",
    about_mission_text: "Brindar a nuestros huéspedes una experiencia única de descanso y conexión con la naturaleza, ofreciendo alojamientos confortables y un servicio cercano en un entorno privilegiado de la dehesa extremeña.",
    about_vision_title: "Nuestra Visión",
    about_vision_text: "Ser el referente en turismo rural de la región, reconocido por promover el bienestar, la sostenibilidad y el valor del entorno natural, convirtiéndonos en el destino favorito para quienes buscan desconectar y redescubrir la tranquilidad.",
    video_fallback: "Tu navegador no soporta la reproducción de video.",
    video_pause_aria: "Pausar video",
    video_play_aria: "Reproducir video",
    services_title: "¿Por qué elegirnos?",
    services_subtitle: "Descubre por qué nuestra casa rural es el refugio perfecto para tu bienestar, tu familia y tus recuerdos.",
    services_peace_title: "Paz y Desconexión Absoluta",
    services_peace_description: "Aléjate del ruido y el estrés de la ciudad. Aquí el único despertador es el canto de los pájaros. Disfruta de un entorno donde se respira tranquilidad y el tiempo transcurre sin prisas.",
    services_peace_highlight: "Sin ruidos urbanos",
    services_nature_title: "Entorno Natural Privilegiado", 
    services_nature_description: "Despierta rodeado por una dehesa con caballos y un lago con patos. Un paisaje extremeño único a tu puerta, ideal para pasear, observar aves y reconectar con la naturaleza.",
    services_nature_highlight: "Fauna autóctona",
    services_security_title: "Seguridad para Toda la Familia",
    services_security_description: "Nuestra finca está completamente vallada, creando un espacio seguro para que los niños jueguen con total libertad. La tranquilidad de los padres están garantizadas.",
    services_security_highlight: "100% seguro",
    about_section_title: "Nuestra Historia",
    service1_title: "Paz y Desconexión Absoluta",
    service1_desc: "Aléjate del ruido y el estrés de la ciudad. Aquí el único despertador es el canto de los pájaros. Disfruta de un entorno donde se respira tranquilidad y el tiempo transcurre sin prisas.",
    service2_title: "Entorno Natural Privilegiado", 
    service2_desc: "Despierta rodeado por una dehesa con caballos y un lago con patos. Un paisaje extremeño único a tu puerta, ideal para pasear, observar aves y reconectar con la naturaleza.",
    service3_title: "Seguridad para Toda la Familia",
    service3_desc: "Nuestra finca está completamente vallada, creando un espacio seguro para que los niños jueguen con total libertad. La tranquilidad de los padres están garantizadas.",
    testimonials_title: "Lo que dicen nuestros huéspedes",
    testimonials_subtitle: "Casa rural con encanto en Extremadura, ideal para escapadas en familia, pareja o con amigos.",
    testimonial1: "Un lugar ideal para descansar en familia, rodeado de naturaleza. Volveremos seguro.",
    faq_title: "Preguntas Frecuentes",
    faq_subtitle: "¿Tienes alguna pregunta? Te la resolvemos.",
    faq_pet_q: "¿Admitís mascotas en los apartamentos?",
    faq_pet_a: "Sí, admitimos mascotas bajo consulta previa. Queremos asegurar que tanto tu mascota como el resto de huéspedes disfruten de una estancia cómoda.",
    faq_pool_q: "La piscina que se menciona, ¿es privada de la casa? ¿Cuándo está abierta?",
    faq_pool_a: "La piscina se encuentra justo enfrente de nuestra casa, es la piscina municipal del pueblo. Es una instalación excelente y muy cómoda por su cercanía. Al ser municipal, su apertura se limita a la temporada de verano (generalmente de mediados de junio a principios de septiembre). El acceso no está incluido en el precio del alojamiento, pero las tarifas son muy asequibles.",
    faq_kitchen_q: "¿Están equipados los apartamentos con todo lo necesario para cocinar y dormir?",
    faq_kitchen_a: "Sí, todos nuestros apartamentos están completamente equipados con cocina funcional, ropa de cama, toallas y todo lo necesario para una estancia confortable.",
    faq_kids_q: "¿Es un lugar seguro y recomendable para ir con niños pequeños?",
    faq_kids_a: "Absolutamente. Nuestra finca está completamente vallada y es un espacio muy seguro para niños. Además, el entorno natural es perfecto para que disfruten al aire libre con total tranquilidad.",
    faq_services_q: "¿Hay supermercados o restaurantes cerca de la casa?",
    faq_services_a: "Sí, en Guijo de Coria encontrarás servicios básicos, y a pocos kilómetros tienes Coria con supermercados, restaurantes y todos los servicios necesarios.",
    faq_checkin_q: "¿Cuáles son los horarios de entrada (check-in) y salida (check-out)?",
    faq_checkin_a: "Check-in: desde las 16:00h. Check-out: hasta las 11:00h. Si necesitas flexibilidad en los horarios, contáctanos y buscaremos la mejor solución.",
    footer_cta_title: "¿Listo para tu Escapada?",
    footer_cta_subtitle: "Reserva ahora tu refugio en la dehesa extremeña",
    footer_whatsapp: "Reservar por WhatsApp",
    footer_info: "Más Información",
    tourism_title: "Donde se detiene el tiempo",
    tourism_subtitle: "Cáceres, ciudad Patrimonio de la Humanidad, te espera a pocos minutos. Vive la magia de la historia con el confort del presente.",
    tourism_discover_caceres: "Descubre Cáceres",
    gallery_title: "Galería",
    gallery_subtitle: "Momentos Únicos",
    gallery_description: "Cada rincón cuenta una historia de tranquilidad y belleza natural",
    gallery_item1_alt: "Interior acogedor del apartamento",
    gallery_item1_title: "Confort Rural",
    gallery_item1_category: "Apartamentos",
    gallery_item1_description: "Espacios diseñados para el descanso",
    gallery_item2_alt: "Piscina privada rodeada de naturaleza",
    gallery_item2_title: "Relax Total",
    gallery_item2_category: "Instalaciones",
    gallery_item2_description: "Disfruta de la piscina en plena dehesa",
    gallery_item3_alt: "Vista de la dehesa extremeña",
    gallery_item3_title: "Naturaleza Pura",
    gallery_item3_category: "Entorno",
    gallery_item3_description: "Paisajes únicos de Extremadura",
    gallery_item4_alt: "Patrimonio histórico de Cáceres",
    gallery_item4_title: "Patrimonio Histórico",
    gallery_item4_category: "Turismo",
    gallery_item4_description: "Descubre la riqueza cultural",
    gallery_item5_alt: "Detalle del salón",
    gallery_item5_title: "Rincones con Encanto",
    gallery_item5_category: "Interiores",
    gallery_item5_description: "Cada detalle está pensado para tu confort",
    gallery_item6_alt: "Cama del dormitorio",
    gallery_item6_title: "Descanso Garantizado",
    gallery_item6_category: "Dormitorios",
    gallery_item6_description: "Habitaciones que invitan a soñar",
    gallery_item7_alt: "Cocina totalmente equipada",
    gallery_item7_title: "Como en Casa",
    gallery_item7_category: "Apartamentos",
    gallery_item7_description: "Equipamiento completo para tu estancia",
    gallery_item8_alt: "Vistas desde el balcón",
    gallery_item8_title: "Amaneceres Únicos",
    gallery_item8_category: "Entorno",
    gallery_item8_description: "Despierta con vistas a la dehesa",
    contact_title: "Contacto",
    contact_subtitle: "Estamos aquí para ayudarte a planificar tu escapada perfecta",
    contact_cta: "Contáctanos",
    feature_certified: "Casa Rural Certificada",
    feature_safe: "100% Seguro para Familias",
    feature_guests: "+150 Huéspedes Satisfechos",
    footer_desc_title: "Casa Lago Guijo de Coria",
    footer_desc_text: "Apartamentos rurales en el corazón de la dehesa extremeña. Tu refugio de paz y descanso.",
    footer_contact_title: "Contacto Rápido",
    footer_contact_phone: "Teléfono",
    footer_contact_email: "Email",
    footer_contact_location: "Ubicación",
    footer_availability_title: "Disponibilidad",
    footer_availability_hours: "Atención: 24/7",
    footer_availability_checkin: "Check-in: 16:00h",
    footer_availability_checkout: "Check-out: 11:00h",
    footer_reviews_title: "Nuestros huéspedes",
    footer_reviews_rating: "5.0 (Excelentes valoraciones)",
    footer_reviews_quote: "Un lugar perfecto para desconectar y disfrutar de la naturaleza.",
    footer_copyright: `© ${new Date().getFullYear()} Casa Lago Guijo de Coria. Todos los derechos reservados.`
  },
  en: {
    nav_inicio: "Home",
    nav_nosotros: "About",
    nav_servicios: "Services", 
    nav_galeria: "Gallery",
    nav_contacto: "Contact",
    hero_title: "Casa Lago Guijo de Coria",
    hero_subtitle: "Rural apartments in Guijo de Coria, a peaceful refuge surrounded by the Extremadura dehesa",
    hero_cta: "Book Now",
    hero_info: "More information",
    about_title: "Breathe. Disconnect. Start again.",
    about_text: "We are a couple who decided to transform this privileged corner of the Extremadura dehesa into a refuge for those who need to stop, breathe and reconnect. At Casa Lago Guijo de Coria we have created cozy rural apartments with attention to detail, promoting a model of responsible and sustainable rural tourism.",
    about_desire: "Our desire is that you enjoy the tranquility of the countryside, the singing of the birds and the calm that only nature can offer, valuing the environment, its traditions and its resources, whether as a couple, with family or with friends.",
    about_mission_title: "Our Mission",
    about_mission_text: "To provide our guests with a unique experience of rest and connection with nature, offering comfortable accommodation and friendly service in a privileged environment of the Extremadura dehesa.",
    about_vision_title: "Our Vision",
    about_vision_text: "To be the benchmark in rural tourism in the region, recognized for promoting well-being, sustainability and the value of the natural environment, becoming the favorite destination for those looking to disconnect and rediscover tranquility.",
    video_fallback: "Your browser does not support video playback.",
    video_pause_aria: "Pause video",
    video_play_aria: "Play video",
    services_title: "Why choose us?",
    services_subtitle: "Discover why our rural house is the perfect refuge for your well-being, your family and your memories.",
    services_peace_title: "Peace and Total Disconnection",
    services_peace_description: "Get away from city noise and stress. Here the only alarm clock is birdsong. Enjoy an environment where tranquility breathes and time passes without rush.",
    services_peace_highlight: "No urban noise",
    services_nature_title: "Privileged Natural Environment", 
    services_nature_description: "Wake up surrounded by a meadow with horses and a lake with ducks. A unique Extremadura landscape at your door, ideal for walking, bird watching and reconnecting with nature.",
    services_nature_highlight: "Native wildlife",
    services_security_title: "Safety for the Whole Family",
    services_security_description: "Our property is completely fenced, creating a safe space for children to play with complete freedom. Parents' peace of mind is guaranteed.",
    services_security_highlight: "100% safe",
    about_section_title: "Our Story",
    service1_title: "Absolute Peace and Disconnection",
    service1_desc: "Get away from the noise and stress of the city. Here the only alarm clock is the singing of birds. Enjoy an environment where you breathe tranquility and time passes without haste.",
    service2_title: "Privileged Natural Environment",
    service2_desc: "Wake up surrounded by a dehesa with horses and a lake with ducks. A unique Extremaduran landscape at your door, ideal for walking, bird watching and reconnecting with nature.", 
    service3_title: "Safety for the Whole Family",
    service3_desc: "Our estate is completely fenced, creating a safe space for children to play with complete freedom. Parents' peace of mind is guaranteed.",
    testimonials_title: "What our guests say",
    testimonials_subtitle: "Charming rural house in Extremadura, ideal for family, couple or friends getaways.",
    testimonial1: "An ideal place to rest as a family, surrounded by nature. We will definitely return.",
    faq_title: "Frequently Asked Questions",
    faq_subtitle: "Do you have any questions? We'll solve them for you.",
    faq_pet_q: "Do you accept pets in the apartments?",
    faq_pet_a: "Yes, we accept pets upon prior consultation. We want to ensure that both your pet and other guests enjoy a comfortable stay.",
    faq_pool_q: "The pool mentioned, is it private to the house? When is it open?",
    faq_pool_a: "The pool is located right in front of our house, it is the town's municipal pool. It is an excellent facility and very convenient due to its proximity. Being municipal, its opening is limited to the summer season (usually from mid-June to early September). Access is not included in the accommodation price, but the rates are very affordable.",
    faq_kitchen_q: "Are the apartments equipped with everything necessary for cooking and sleeping?",
    faq_kitchen_a: "Yes, all our apartments are fully equipped with a functional kitchen, bed linen, towels and everything necessary for a comfortable stay.",
    faq_kids_q: "Is it a safe and recommended place to go with small children?",
    faq_kids_a: "Absolutely. Our farm is completely fenced and is a very safe space for children. In addition, the natural environment is perfect for them to enjoy the outdoors with complete peace of mind.",
    faq_services_q: "Are there supermarkets or restaurants near the house?",
    faq_services_a: "Yes, in Guijo de Coria you will find basic services, and a few kilometers away you have Coria with supermarkets, restaurants and all the necessary services.",
    faq_checkin_q: "What are the check-in and check-out times?",
    faq_checkin_a: "Check-in: from 4:00 p.m. Check-out: until 11:00 a.m. If you need flexibility in schedules, contact us and we will find the best solution.",
    footer_cta_title: "Ready for your Getaway?",
    footer_cta_subtitle: "Book now your refuge in the Extremaduran dehesa",
    footer_whatsapp: "Book via WhatsApp",
    footer_info: "More Information",
    tourism_title: "Where time stops",
    tourism_subtitle: "Cáceres, World Heritage city, awaits you just minutes away. Experience the magic of history with the comfort of the present.",
    tourism_discover_caceres: "Discover Cáceres",
    gallery_title: "Gallery",
    gallery_subtitle: "Unique Moments",
    gallery_description: "Every corner tells a story of tranquility and natural beauty",
    gallery_item1_alt: "Cozy interior of the apartment",
    gallery_item1_title: "Rural Comfort",
    gallery_item1_category: "Apartments",
    gallery_item1_description: "Spaces designed for rest",
    gallery_item2_alt: "Private pool surrounded by nature",
    gallery_item2_title: "Total Relaxation",
    gallery_item2_category: "Facilities",
    gallery_item2_description: "Enjoy the pool in the middle of the dehesa",
    gallery_item3_alt: "View of the Extremadura dehesa",
    gallery_item3_title: "Pure Nature",
    gallery_item3_category: "Environment",
    gallery_item3_description: "Unique landscapes of Extremadura",
    gallery_item4_alt: "Historical heritage of Cáceres",
    gallery_item4_title: "Historical Heritage",
    gallery_item4_category: "Tourism",
    gallery_item4_description: "Discover the cultural richness",
    gallery_item5_alt: "Detail of the living room",
    gallery_item5_title: "Charming Corners",
    gallery_item5_category: "Interiors",
    gallery_item5_description: "Every detail is designed for your comfort",
    gallery_item6_alt: "Bedroom bed",
    gallery_item6_title: "Guaranteed Rest",
    gallery_item6_category: "Bedrooms",
    gallery_item6_description: "Rooms that invite you to dream",
    gallery_item7_alt: "Fully equipped kitchen",
    gallery_item7_title: "Like at Home",
    gallery_item7_category: "Apartments",
    gallery_item7_description: "Complete equipment for your stay",
    gallery_item8_alt: "Views from the balcony",
    gallery_item8_title: "Unique Sunrises",
    gallery_item8_category: "Environment",
    gallery_item8_description: "Wake up with views of the dehesa",
    contact_title: "Contact",
    contact_subtitle: "We are here to help you plan your perfect getaway",
    contact_cta: "Contact Us",
    feature_certified: "Certified Rural House",
    feature_safe: "100% Safe for Families",
    feature_guests: "+150 Satisfied Guests",
    footer_desc_title: "Casa Lago Guijo de Coria",
    footer_desc_text: "Rural apartments in the heart of the Extremadura dehesa. Your refuge of peace and rest.",
    footer_contact_title: "Quick Contact",
    footer_contact_phone: "Phone",
    footer_contact_email: "Email",
    footer_contact_location: "Location",
    footer_availability_title: "Availability",
    footer_availability_hours: "Service: 24/7",
    footer_availability_checkin: "Check-in: 4:00 PM",
    footer_availability_checkout: "Check-out: 11:00 AM",
    footer_reviews_title: "Our Guests",
    footer_reviews_rating: "5.0 (Excellent ratings)",
    footer_reviews_quote: "A perfect place to disconnect and enjoy nature.",
    footer_copyright: `© ${new Date().getFullYear()} Casa Lago Guijo de Coria. All rights reserved.`
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'es',
  setLanguage: () => {},
  t: () => ''
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'es' | 'en'>('es');
  
  const t = (key: string) => {
    return translations[language][key as keyof typeof translations.es] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const LanguageToggle: React.FC = () => {
  const { language, setLanguage } = useLanguage();
  
  return (
    <Button
      variant="ghost"
      size="sm"
      onClick={() => setLanguage(language === 'es' ? 'en' : 'es')}
      className="gap-1"
    >
      <Globe className="h-4 w-4" />
      {language.toUpperCase()}
    </Button>
  );
};